# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32441f6e05559a7b4fd5984ebcaec3de3205be9b06bd3add40f935e44b48639e018816a62983fb7c44fa19f28eef6448c2f91e99be7463133db9d1436932eceb

test:
  secret_key_base: 3ec21e01d3fcdd9059040659d2acb8b4a3fde36de983948e77d832045a07c8fb4e54a7ff17e422bc016714935700f14411c5afb3e743c4122945612472cf1557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
